const POPUP = {
    ABOUT: 'POPUP_ABOUT',
    LOADING: 'POPUP_LOADING',
    WARNING: 'POPUP_WARNING',
    ERROR_EXPORTING: 'POPUP_ERROR_EXPORTING',
    ERROR_SPLIT: 'POPUP_ERROR_SPLIT'
};

export {POPUP};
