import EventEmitter from "eventemitter3";

const EVENT = {
    ATLAS_LIST_CHANGED: 'ATLAS_LIST_CHANGED',
    PACK_COMPLETED: 'PACK_COMPLETED',
    PACK_OPTIONS_CHANGED: 'PACK_OPTIONS_CHANGED',
    MULTIFONT_ACTIVATED: 'MULTIFONT_ACTIVATED',
    START_EXPORT: 'START_EXPORT',
    EXPORT_COMPLETED: 'EXPORT_COMPLETED',
    FONT_SELECTED: 'FONT_SELECTED',
    CHAR_SELECTED: 'CHAR_SELECTED',
    CHAR_CHANGED: 'CHAR_CHANGED',
    UPDATE_RESULT: 'UPDATE_RESULT',
    BACKGROUND_TEXTURE_CHANGED: 'BACKGROUND_TEXTURE_CHANGED',
    SHOW_POPUP: 'SHOW_POPUP',
    CLOSE_POPUP: 'CLOSE_POPUP'
};

const Observer = new EventEmitter();

export {
    Observer,
    EVENT
}

